# -*- coding: utf-8 -*-
"""pagerank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1871n1rIQnT8H8FWmHtOP-QGFdgrbRJZd
"""

import numpy as np
m=np.array([[0,1,0],[0.5,0,0.5],[0,1,0]])

alpha=0.5
n=3
S=alpha/3+(1-alpha)*m

S

pr0=np.array([1/3,1/3,1/3])

while(1):
  pr=pr0
  pr0=np.matmul(pr0,S)
  print(pr0)
  flag=0
  for i in range(len(pr)):
    if pr0[i]-pr[i]>0.01:
      flag=1
  if flag==0:
    break

pr0

sum(pr0)

