# -*- coding: utf-8 -*-
"""HITS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O3vXVbI3O85_LLbgGwF5h7-2YB9Ww6lA
"""

import numpy as np
A=np.array([[0,1,1,1],[0,0,1,1],[0,1,0,0],[1,0,1,0]])
AT=np.transpose(A)
print(AT)

h=[1,1,1,1]
a=[1,1,1,1]

for i in range(10):
  h0=h
  h=np.matmul(A,a)
  print(h)
  a=np.matmul(AT,h0)
  print(a)
  h=h/sum(h)
  a=a/sum(a)

h

a

